name: Tests

on: [push]

jobs:
  linux:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Socket SDK deps
      run: |
        sudo apt install software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt install gcc-12 g++-12 libwebkit2gtk-4.0-dev libcurl4-openssl-dev

    - name: Setup Socket SDK
      run: |
        git config --global user.email "devops@socketsupply.co"
        git config --global user.name "Socket Supply, Co - Github Actions"
        ## @TODO(jwerle): change branch when stable
        git clone --branch dev --depth 1 git@github.com:socketsupply/socket-sdk.git
        cd socket-sdk
        ./bin/install.sh
        cd ..

    - name: npm install
      run: npm install

    - name: npm test
      run: |
        npm test --silent

      env:
        CI: true
        CXX: g++-12

  mac:
    runs-on: macOS-12
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Socket SDK deps
      run: |
        brew install automake

    - name: Setup Socket SDK
      run: |
        git config --global user.email "devops@socketsupply.co"
        git config --global user.name "Socket Supply, Co - Github Actions"
        ## @TODO(jwerle): change branch when stable
        git clone --branch dev --depth 1 git@github.com:socketsupply/socket-sdk.git
        cd socket-sdk
        ./bin/install.sh
        cd ..

    - name: npm install
      run: npm install

    - name: npm test
      run: |
        npm test --silent

      env:
        CI: true

  android:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 18

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Socket SDK deps
      run: |
        sudo apt install software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt install gcc-12 g++-12 libwebkit2gtk-4.0-dev libcurl4-openssl-dev

    - name: Setup Socket SDK
      run: |
        git config --global user.email "devops@socketsupply.co"
        git config --global user.name "Socket Supply, Co - Github Actions"
        ## @TODO(jwerle): change branch when stable
        git clone --branch dev --depth 1 git@github.com:socketsupply/socket-sdk.git
        cd socket-sdk
        ./bin/install.sh
        cd ..

    - name: npm install
      run: npm install

    - name: npm test
      run: |
        npm run test:android-emulator --silent

      env:
        CI: true
        CXX: g++-12
